
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhtxjvqxylkyegpjvkpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRodHhqdnF4eWxreWVncGp2a3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODg3NDIsImV4cCI6MjA2MzQ2NDc0Mn0.9Y8_5fJVjHcfyMRWlxWEfUXNy49xvI6WOb_l11eIyHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
